### ISSUE TITLE
next lesson button

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/swift-optionalFunc-readme#2]
the next lesson button doesn't move to the next lesson.

**Comment by AnnJohn** [comment]
@susanlovaglio tried it on my end on the student side and it worked fine for me. I'm going to close this for now and if students raise it, then i'll flag to product

**Comment by susanlovaglio** [comment]
I thought about it and it was probably an issue with my browser. Because i had the problem with another one and i quit and restarted and it worked. Thanks Ann!
